# Generated by Django 5.1.4 on 2024-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowHighBudget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='from_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='high_budget_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='high_budget_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='high_budget_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
