# Generated by Django 5.1.4 on 2024-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCQuotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_pdf', models.FileField(upload_to='quotations/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
