# Generated by Django 5.1.2 on 2024-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=100)),
                ('person_responsible', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
