# Generated by Django 5.1.4 on 2024-12-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('pdf_link', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('institutional_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
