# Generated by Django 5.1.4 on 2024-12-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('to_address', models.TextField()),
                ('instruments', models.CharField(max_length=255)),
                ('quotation_no', models.CharField(max_length=255)),
                ('quotation_date', models.DateField()),
                ('branchname', models.CharField(max_length=255)),
                ('terms', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total_no_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='purchase_order_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hsn_code', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder')),
            ],
        ),
    ]
